import { sanitizeErrorText } from '../../public/js/proof-error-sanitizer.js';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFileSync } from 'node:fs';
import { runInNewContext } from 'node:vm';
import { tmpdir } from 'node:os';
import express from 'express';

process.env.DATABASE_PATH = `${tmpdir()}/proof-errors-${process.pid}-${Date.now()}.db`;
process.env.SNAPSHOT_DIR = `${tmpdir()}/proof-errors-snapshots-${process.pid}`;
Object.assign(process.env, { PROOF_ENV: 'test', PROOF_DB_ENV_INIT: 'test', PROOF_FEEDBACK_ENABLED: '1', PROOF_TRUST_PROXY_HEADERS: '1', SOMA_ADMIN_TOKEN: 'never-send' });
const root = '../../server';
const { clientErrorRoutes, ERROR_WINDOW_MS, sanitizeClientError } = await import(`${root}/client-errors.js`);
const { getDb } = await import(`${root}/db.js`);
const nativeFetch = globalThis.fetch;
const forwarded: any[] = [];
let down = false;
globalThis.fetch = async (input, init) => {
  assert.equal(String(input), 'http://127.0.0.1:4252/feedback');
  forwarded.push(JSON.parse(String(init?.body)));
  assert.equal((init?.headers as any).Authorization, undefined);
  if (down) throw new Error('offline');
  return Response.json({ status: 'accepted', build: false });
};
const app = express(); app.use(express.json(), clientErrorRoutes);
const server = createServer(app);
await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${(server.address() as any).port}`;
let address = 0;
async function report(body: any, ip = `198.51.100.${address++}`, extra = {}) {
  const response = await nativeFetch(origin + '/api/client-error', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin, 'X-Forwarded-For': ip, ...extra }, body: JSON.stringify(body) });
  return { status: response.status, json: await response.json().catch(() => null) };
}
try {
  const privateMessage = 'Index 9 out of range for <"CONFIDENTIAL document sentence">';
  assert.equal((await report({ message: privateMessage, stack: privateMessage + '\n at update (https://site.test/editor.js?token=SECRET:9:3)' })).status, 202);
  const privateSample = getDb().prepare('SELECT sample FROM client_errors').get().sample;
  assert(!privateSample.includes('CONFIDENTIAL'));
  assert(!JSON.stringify(forwarded).includes('CONFIDENTIAL'));
  assert(!JSON.stringify(forwarded).includes('SECRET'));
  assert(forwarded.at(-1).text.includes('editor.js:9:3'));
  getDb().prepare('DELETE FROM client_errors').run();
  const large = { message: 'm!'.repeat(450), stack: '😀'.repeat(3000), url: 'https://site.test/d/slug?token=secret#fragment', page: '/d/slug?token=secret', build: 'build-a', userAgent: 'agent', area: 'editor', text: 'DO NOT STORE DOCUMENT TEXT', adminToken: 'fake' };
  assert.equal((await report(large)).status, 202);
  let row = getDb().prepare('SELECT * FROM client_errors').get();
  let sample = JSON.parse(row.sample);
  assert.equal(sample.message.length, 500); assert(Buffer.byteLength(sample.stack) <= 4096);
  assert.equal(sample.url, 'https://site.test/d/slug'); assert.equal(sample.page, '/d/slug');
  assert(!row.sample.includes('secret')); assert(!row.sample.includes('DO NOT STORE')); assert(!row.sample.includes('fake'));
  const payload = { message: 'failed https://site.test/x?token=secret', stack: 'Error: failed\n    at update (https://site.test/app.js?token=secret:1:2)\n    at run (/assets/runtime.js?secret=yes)', url: large.url, page: large.page, build: 'build-b', area: 'editor' };
  const result = await report(payload);
  assert.equal(result.json.accepted, true);
  for (const key of Object.keys(sanitizeClientError(payload))) assert(!sanitizeClientError(payload)[key].includes('?'));
  const last = forwarded.at(-1);
  assert.equal(last.site, 'proof-plus'); assert.equal(last.area, 'error');
  assert(last.text.includes('build-b')); assert(last.text.includes('at update')); assert(!JSON.stringify(last).includes('secret')); assert(!('adminToken' in last));
  const countBefore = forwarded.length;
  const duplicates = await Promise.all(Array.from({ length: 4 }, () => report({ ...payload, url: 'https://site.test/d/other?secret=other' })));
  assert(duplicates.every(result => result.json.duplicate && result.json.accepted));
  assert.equal(forwarded.length, countBefore);
  row = getDb().prepare('SELECT * FROM client_errors WHERE sample LIKE ?').get('%build-b%');
  assert.equal(row.count, 5); assert(row.last_seen >= row.first_seen);
  getDb().prepare('UPDATE client_errors SET first_seen=? WHERE signature=?').run(Date.now() - ERROR_WINDOW_MS - 1, row.signature);
  await report(payload); assert.equal(forwarded.length, countBefore + 1);
  assert.equal(getDb().prepare('SELECT count FROM client_errors WHERE signature=?').get(row.signature).count, 1);
  for (let i = 0; i < 20; i++) assert.equal((await report({ message: 'rate-error' }, '203.0.113.9')).status, 202);
  assert.equal((await report({ message: 'rate-error' }, '203.0.113.9')).status, 429);
  assert.equal((await report({ message: 'rate-error' }, '203.0.113.10')).status, 202, 'nginx clients have independent buckets');
  assert.equal((await report(payload, undefined, { Origin: '' })).status, 403);
  down = true;
  assert.equal((await report({ message: 'service-down' })).status, 502);
  assert.equal((await report({ message: 'service-down' })).json.accepted, false, 'never claim offline report reached the builder');
  process.env.PROOF_FEEDBACK_ENABLED = '0'; assert.equal((await report(payload)).status, 404);

  const events: Record<string, Function> = {};
  const posts: any[] = [], banners: any[] = [];
  const window: any = { PROOF_CLIENT_ERRORS: { area: 'editor', build: 'browser-build' }, addEventListener: (name: string, handler: Function) => events[name] = handler };
  const document = { createElement: () => ({ textContent: '', style: {}, append(text: string) { this.textContent += text; }, remove() {} }), body: { appendChild: (node: any) => banners.push(node) } };
  const browserConsole = { error: () => {} };
  const source = readFileSync(new URL('../../public/js/proof-client-errors.js', import.meta.url), 'utf8');
  runInNewContext(source.replace(/^import .*;\n/, ''), { sanitizeErrorText, window, document, console: browserConsole, location: { origin: 'https://site.test', pathname: '/d/test', search: '?token=secret' }, navigator: { userAgent: 'test' }, fetch: async (_: any, init: any) => { posts.push(JSON.parse(init.body)); return { ok: true, json: async () => ({ accepted: true }) }; } });
  await window.proofReportClientError(privateMessage, privateMessage + '\n at update (/editor.js?token=SECRET:9:3)');
  assert.equal(posts[0].message, 'Index 9 out of range for [text]');
  assert.equal(posts[0].stack, ' at update (/editor.js:9:3)');
  assert(!JSON.stringify(posts).includes('CONFIDENTIAL'));
  events.error({ message: 'window-error', error: { stack: 'Error: private duplicate message\n at fn (https://site.test/app.js?token=secret)' }, document: 'NEVER SEND' });
  await window.proofReportClientError('window-error', 'Error: private duplicate message\n at fn (https://site.test/app.js?token=secret)');
  assert.equal(posts.length, 2, 'banner and event share a report');
  events.unhandledrejection({ reason: { message: 'rejected', stack: ' at rejected (/app.js?secret=secret)' } });
  (browserConsole.error as any)('Caught error while handling a Yjs update', { message: 'bad update', stack: ' at apply (/app.js?token=secret)', document: 'NEVER SEND' }, 'NEVER SEND');
  await window.proofReportClientError('Caught error while handling a Yjs update: bad update', ' at apply (/app.js?token=secret)');
  assert(banners[0].textContent.includes('Reported to the builder.'));
  for (let i = 0; i < 10; i++) await window.proofReportClientError(`extra-${i}`, '');
  assert.equal(posts.length, 5);
  assert(!JSON.stringify(posts).includes('secret')); assert(!JSON.stringify(posts).includes('NEVER SEND')); assert(!JSON.stringify(posts).includes('private duplicate'));
  assert(posts.every(post => post.page === '/d/test' && post.area === 'editor' && post.build === 'browser-build'));
  console.log('Client error server and browser runtime tests passed');
} finally {
  globalThis.fetch = nativeFetch;
  await new Promise<void>(resolve => server.close(() => resolve()));
}
